name: webapp
image: clux/webapp-rs
version: 0.2.0
metadata:
  team: observability
  repo: https://github.com/clux/webapp-rs

# kubernetes resources
resources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    cpu: 50m
    memory: 100Mi

controller:
  replicas: 1

# health check used to gate upgrades / readinessProbe
health:
  uri: /health
  port: 8081
  wait: 0

# exposed Service port
httpPort: 8080

# template the config file into /
configMap:
  mount: /
  files:
  - name: Rocket.toml.j2
    dest: Rocket.toml

# what regions it's deployed to
regions:
  - minikube
#- kind

# evars
env:
  DATABASE_URL: IN_VAULT
  DATABASE_PASSWORD: IN_VAULT
  NAMESPACE: apps

#vault:
  #enabled: true
  #secrets:
    #- path: secret/minikube/webapp
      #kvVersion: 2
      #envVars:
        #- name: DATABASE_URL
          #key: database_url
        #- name: DATABASE_PASSWORD
          #key: database_password