apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: minikubes.minikube.shipcat.io
spec:
  group: minikube.shipcat.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                size:
                  type: string
  scope: Namespaced
  names:
    plural: minikubes
    singular: minikube
    kind: Minikube
    shortNames:
      - mk