apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
{{- template "chart.shipcatRefs" . }}
{{- if .Values.rbac }}
automountServiceAccountToken: true
{{- else }}
automountServiceAccountToken: false
{{- end }}
